// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information

enum QUESTION_TYPE
{
	MATH_K,
	MATH_1,
	MATH_2,
	MATH_3,
	MATH_4,
	MATH_5
}

global.questionArr = [
	new Question("What is 3 + 6?", 9, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 3 + 7?", 10, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 5 + 2?", 7, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 5 - 2?", 3, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 6 + 4?", 10, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 2 + 3?", 5, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 8 - 3?", 5, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 7 - 4?", 3, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 4 + 5?", 9, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 10 - 3?", 7, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 4 + 6?", 10, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 9 - 5?", 4, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 2 + 9?", 11, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 1 + 7?", 8, 4, false, QUESTION_TYPE.MATH_K),
	new Question("What is 12 - 6?", 6, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 10 + 5?", 15, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 9 + 8?", 17, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 13 - 7?", 6, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 14 - 5?", 9, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 15 + 3?", 18, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 4 + 8?", 12, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 19 - 9?", 10, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 6 + 9?", 15, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 17 - 8?", 9, 4, false, QUESTION_TYPE.MATH_1),
	new Question("What is 16 - 5?", 11, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 18 + 2?", 20, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 25 - 9?", 16, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 14 + 6?", 20, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 21 - 11?", 10, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 23 + 7?", 30, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 30 - 15?", 15, 3, false, QUESTION_TYPE.MATH_2),
	new Question("What is 28 - 12?", 16, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 35 + 4?", 39, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 40 - 19?", 21, 4, false, QUESTION_TYPE.MATH_2),
	new Question("What is 12 x 3?", 36, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 8 x 5?", 40, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 15 / 3?", 5, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 9 x 4?", 36, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 27 / 9?", 3, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 11 x 6?", 66, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 18 / 2?", 9, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 24 / 6?", 4, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 12 x 8?", 96, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 56 / 7?", 8, 4, false, QUESTION_TYPE.MATH_3),
	new Question("What is 27 / 3?", 9, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 45 / 5?", 9, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 36 / 4?", 9, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 30 x 5?", 150, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 75 / 3?", 25, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 9 x 12?", 108, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 18 x 4?", 72, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 56 / 8?", 7, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 64 / 8?", 8, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 81 / 9?", 9, 4, false, QUESTION_TYPE.MATH_4),
	new Question("What is 125 / 5?", 25, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 36 / 6?", 6, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 15 x 18?", 270, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 98 / 7?", 14, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 72 / 9?", 8, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 150 / 5?", 30, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 18 x 15?", 270, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 144 / 12?", 12, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 11 x 9?", 99, 4, false, QUESTION_TYPE.MATH_5),
	new Question("What is 48 / 8?", 6, 4, false, QUESTION_TYPE.MATH_5)
]